# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/slugs', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Slug. As you add validations to Slug, be sure to
  # adjust the attributes here as well.

  before(:all) do
    @user = FactoryBot.create(:user)
    sign_in @user
  end

  let(:auth_headers) { @user.create_new_auth_token }
  let(:valid_attributes) do
    {
      name: 'Corporate name'
    }
  end

  let(:invalid_attributes) do
    {
      name: 123
    }
  end

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # SlugsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) do
    {
      'Uid' => auth_headers['uid'],
      'Access-Token' => auth_headers['access-token'],
      'Client' => auth_headers['client']
    }
  end

  let(:invalid_headers) do
    {
      'Uid' => auth_headers['uid']
    }
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      FactoryBot.create(:slug)
      get '/api/v1/slugs', headers: valid_headers, as: :json
      expect(response).to be_successful
    end

    it 'renders a unauthorized status' do
      FactoryBot.create(:slug)
      get '/api/v1/slugs', headers: invalid_headers, as: :json
      expect(response).to have_http_status(:unauthorized)
    end

    it 'renders a successful response with search ' do
      Slug.create! valid_attributes
      get '/api/v1/slugs?search=Corporate', headers: valid_headers, as: :json
      result = JSON.parse(response.body)
      expect(result['data'].count).to eq(1)
    end
  end

  describe 'GET Slug by ID' do
    it 'renders a successful response' do
      slug = FactoryBot.create(:slug)
      get "/api/v1/slugs/#{slug.id}", headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Slug' do
        expect do
          post '/api/v1/slugs',
               params: { slug: valid_attributes }, headers: valid_headers, as: :json
        end.to change(Slug, :count).by(1)
      end

      it 'renders a JSON response with the new slug' do
        post '/api/v1/slugs',
             params: { slug: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Slug' do
        expect do
          post '/api/v1/slugs',
               params: { slug: invalid_attributes }, as: :json
        end.to change(Slug, :count).by(0)
      end

      it 'renders a JSON response with errors for the new slug' do
        post '/api/v1/slugs',
             params: { slug: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq('application/json; charset=utf-8')
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        {
          name: 'New corporate name'
        }
      end

      it 'updates the requested slug' do
        slug = FactoryBot.create(:slug)
        patch "/api/v1/slugs/#{slug.id}",
              params: { slug: new_attributes }, headers: valid_headers, as: :json
        slug.reload
        expect(slug.attributes).to include({ 'name' => 'New corporate name' })
      end

      it 'renders a JSON response with the slug' do
        slug = FactoryBot.create(:slug)
        put "/api/v1/slugs/#{slug.id}",
            params: { slug: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end

    context 'with invalid parameters' do
      it 'renders a JSON response with errors for the slug' do
        slug = FactoryBot.create(:slug)
        patch "/api/v1/slugs/#{slug.id}",
              params: { slug: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq('application/json; charset=utf-8')
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested slug' do
      slug = FactoryBot.create(:slug)
      expect do
        delete "/api/v1/slugs/#{slug.id}", headers: valid_headers, as: :json
      end.to change(Slug, :count).by(-1)
    end
  end
end
